# Text data cleaning and preprocessing

Using the OffensEval, dataset the first task is to prepare and clean the data for further use.

Importing the dataset and removing unnecessary columns.

subtasks b and c labels are not necessary for detecting offensive language.

In [26]:
import pandas as pd
import pickle

tweets_data = pd.read_csv('../Dataset/olid-training-v1.0.tsv', delimiter='\t')
print(tweets_data)
tweets_data = tweets_data.iloc[:,1:3]
test_set = pd.read_csv('../Dataset/testset-levela.tsv', delimiter='\t')
tweets_data

          id                                              tweet subtask_a  \
0      86426  @USER She should ask a few native Americans wh...       OFF
1      90194  @USER @USER Go home youâ€™re drunk!!! @USER #MAG...       OFF
2      16820  Amazon is investigating Chinese employees who ...       NOT
3      62688  @USER Someone should'veTaken" this piece of sh...       OFF
4      43605  @USER @USER Obama wanted liberals &amp; illega...       NOT
...      ...                                                ...       ...
13235  95338  @USER Sometimes I get strong vibes from people...       OFF
13236  67210  Benidorm âœ…  Creamfields âœ…  Maga âœ…   Not too sh...       NOT
13237  82921  @USER And why report this garbage.  We don't g...       OFF
13238  27429                                        @USER Pussy       OFF
13239  46552  #Spanishrevenge vs. #justice #HumanRights and ...       NOT

      subtask_b subtask_c
0           UNT       NaN
1           TIN       IND
2           NaN       NaN
3           UNT       NaN
4           NaN       NaN
...         ...       ...
13235       TIN       IND
13236       NaN       NaN
13237       TIN       OTH
13238       UNT       NaN
13239       NaN       NaN

[13240 rows x 5 columns]

                                                   tweet subtask_a
0      @USER She should ask a few native Americans wh...       OFF
1      @USER @USER Go home youâ€™re drunk!!! @USER #MAG...       OFF
2      Amazon is investigating Chinese employees who ...       NOT
3      @USER Someone should'veTaken" this piece of sh...       OFF
4      @USER @USER Obama wanted liberals &amp; illega...       NOT
...                                                  ...       ...
13235  @USER Sometimes I get strong vibes from people...       OFF
13236  Benidorm âœ…  Creamfields âœ…  Maga âœ…   Not too sh...       NOT
13237  @USER And why report this garbage.  We don't g...       OFF
13238                                        @USER Pussy       OFF
13239  #Spanishrevenge vs. #justice #HumanRights and ...       NOT

[13240 rows x 2 columns]

In [25]:
tweets_data.sample(5)

                                                   tweet subtask_a
6594     @USER You are a bad ass! Keep fighting for us ðŸ’•       OFF
3590   @USER Thank you for saving the dogs!!!!why are...       OFF
13072                     @USER Goofyâ€™s grandfather. URL       NOT
7728   @USER @USER @USER If so why do Democrats conti...       OFF
3488   @USER @USER Abso-fucking-lutely. That shit was...       OFF

In [8]:
test_set

        id                                              tweet
0    15923  #WhoIsQ #WheresTheServer #DumpNike #DECLASFISA...
1    27014  #ConstitutionDay is revered by Conservatives, ...
2    30530  #FOXNews #NRA #MAGA #POTUS #TRUMP #2ndAmendmen...
3    13876  #Watching #Boomer getting the news that she is...
4    60133  #NoPasaran: Unity demo to oppose the far-right...
..     ...                                                ...
855  73439  #DespicableDems lie again about rifles. Dem Di...
856  25657  #MeetTheSpeakers ðŸ™Œ @USER will present in our e...
857  67018  3 people just unfollowed me for talking about ...
858  50665  #WednesdayWisdom Antifa calls the right fascis...
859  24583      #Kavanaugh typical #liberals , #Democrats URL

[860 rows x 2 columns]

Tweets have garbage text on them like user tags (@USER), emojis, and punctuation marks.
To clean this a function to remove unnecessary characters and useless stuff from text is created.

In [9]:
import re 
import string 

#Unicode for emojis, can be used for regex patterns
EMOJI_PATTERN = re.compile(
    "["
    "\U0001F1E0-\U0001F1FF"  # flags (iOS)
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F680-\U0001F6FF"  # transport & map symbols
    "\U0001F700-\U0001F77F"  # alchemical symbols
    "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
    "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
    "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
    "\U0001FA00-\U0001FA6F"  # Chess Symbols
    "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
    "\U00002702-\U000027B0"  # Dingbats
    "\U000024C2-\U0001F251" 
    "]+"
    )

def clean_text(text):
    #Remove @USER
    text = text.replace('@USER','')
    #Remove hastags
    text = re.sub('#\w+','',text)
    #Remove emoji
    text = re.sub(EMOJI_PATTERN,'',text)
    #Remove white space
    text = re.sub('\s+',' ',text)
    #Beginning of the text white space
    text = re.sub('^\s+',' ',text)
    #Remove URL
    text = re.sub('URL','',text)
    #Remove punctuation marks
    text = re.sub('[.,\/#!$%"\?@\^&\*\+;:{}=\-_`~()]','',text)
    #Remove digits
    text = re.sub('\d','',text)
    #Lowercase
    text = text.lower()
    
    return text

#lambda function to apply to dataframes
clean = lambda x: clean_text(x)

In [10]:
tweets_data.tweet = tweets_data.tweet.apply(clean) #Applying cleaning function
test_set.tweet = test_set.tweet.apply(clean)

Separating the dataset into offensive and not offensive language

In [11]:
off_tweets = tweets_data.loc[tweets_data['subtask_a'] == "OFF"]
off_tweets

                                                   tweet subtask_a
0       she should ask a few native americans what th...       OFF
1                                  go home youâ€™re drunk        OFF
3       someone should'vetaken this piece of shit to ...       OFF
5                               liberals are all kookoo        OFF
6                                     oh noes tough shit       OFF
...                                                  ...       ...
13223   is advocating for conduct within bounds of hu...       OFF
13227   liars like the antifa twins you vigorously de...       OFF
13235   sometimes i get strong vibes from people and ...       OFF
13237   and why report this garbage we don't give a crap       OFF
13238                                              pussy       OFF

[4400 rows x 2 columns]

In [12]:
not_tweets = tweets_data.loc[tweets_data['subtask_a'] == "NOT"]
not_tweets

                                                   tweet subtask_a
2      amazon is investigating chinese employees who ...       NOT
4       obama wanted liberals amp illegals to move in...       NOT
8                                      buy more icecream       NOT
10             itâ€™s not my fault you support gun control       NOT
11      whatâ€™s the difference between and one of thes...       NOT
...                                                  ...       ...
13232         she is not the brightest light on the tree       NOT
13233   if i say you are mad now you will say i'm tir...       NOT
13234         retweet complete amp followed all patriots       NOT
13236  benidorm creamfields maga not too shabby of a ...       NOT
13239                                       vs and is a        NOT

[8840 rows x 2 columns]

## Corpus of text

Extracting only tweets for corpus and text cleaning of tweets

In [13]:
only_tweets = pd.DataFrame(tweets_data.tweet)
only_tweets

                                                   tweet
0       she should ask a few native americans what th...
1                                  go home youâ€™re drunk
2      amazon is investigating chinese employees who ...
3       someone should'vetaken this piece of shit to ...
4       obama wanted liberals amp illegals to move in...
...                                                  ...
13235   sometimes i get strong vibes from people and ...
13236  benidorm creamfields maga not too shabby of a ...
13237   and why report this garbage we don't give a crap
13238                                              pussy
13239                                       vs and is a

[13240 rows x 1 columns]

In [14]:
only_tweets_off = pd.DataFrame(off_tweets.tweet)
only_tweets

                                                   tweet
0       she should ask a few native americans what th...
1                                  go home youâ€™re drunk
2      amazon is investigating chinese employees who ...
3       someone should'vetaken this piece of shit to ...
4       obama wanted liberals amp illegals to move in...
...                                                  ...
13235   sometimes i get strong vibes from people and ...
13236  benidorm creamfields maga not too shabby of a ...
13237   and why report this garbage we don't give a crap
13238                                              pussy
13239                                       vs and is a

[13240 rows x 1 columns]

In [15]:
only_tweets_not = pd.DataFrame(not_tweets.tweet)
only_tweets_not

                                                   tweet
2      amazon is investigating chinese employees who ...
4       obama wanted liberals amp illegals to move in...
8                                      buy more icecream
10             itâ€™s not my fault you support gun control
11      whatâ€™s the difference between and one of thes...
...                                                  ...
13232         she is not the brightest light on the tree
13233   if i say you are mad now you will say i'm tir...
13234         retweet complete amp followed all patriots
13236  benidorm creamfields maga not too shabby of a ...
13239                                       vs and is a

[8840 rows x 1 columns]

Exporting the clean corpus of all tweets and replacing the tweets column in the reduced training set

In [16]:
tweets_data.to_csv('tweets_data_clean.csv')
test_set.to_csv('test_clean.csv')
only_tweets.to_csv('only_tweets.csv')
only_tweets_off.to_csv('only_tweets_off.csv')
only_tweets_not.to_csv('only_tweets_not.csv')

Pickling corpus of tweets

In [17]:
only_tweets.to_pickle("corpus.pkl")
only_tweets_not.to_pickle("corpus_not.pkl")
only_tweets_off.to_pickle("corpus_off.pkl")